# 布尔运算符
print("-------与-------")
print(True and True)
print(True and False)
print(False and False)
print("-------或-------")
print(True or True)
print(True or False)
print(False or False)
print("-------非-------")
print(not True)
print(not False)
print("-------in-------")
s = "HelloWorld"
print("W" in s)
print("k" in s)
print("W" not in s)
print("k" not in s)
print("-------位运算-------")
print(4 & 8)
print(4 | 8)
print(4 << 1)
print(4 >> 1)
print(-4 >> 2)
